#ifndef PARAMS_H
#define PARAMS_H

#define PARAM_N 1024

#define PARAM_K 16

#define PARAM_Q 12289 

#define POLY_BYTES 1792

#define BLISS_SEEDBYTES 32

#define BLISS_SEEDBYTES 32
#define BLISS_RECBYTES 256

#define BLISS_SENDABYTES (POLY_BYTES + BLISS_SEEDBYTES)
#define BLISS_SENDBBYTES (POLY_BYTES + BLISS_RECBYTES)


#endif
